safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:     /
url: http://localhost:4000


name: √Åtila Fassina
description: My personal blog/site/lab!

author:
  name: atilafassina
  email: hey@atilafassina.com
  github: atilafassina
  twitter: atilafassina

future:      true
paginate: 5
permalink: /:title/

# Markdown library
markdown: maruku
  # use_tex:    false
  # use_divs:   false
  # png_engine: blahtex
  # png_dir:    images/latex
  # png_url:    /images/latex

# Use Pygments to highlight code blocks
pygments: true
